# Generated by Django 4.0.5 on 2022-06-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Proverb",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("yoruba", models.CharField(max_length=700)),
                ("english", models.CharField(max_length=700)),
                ("wisdom", models.CharField(max_length=700)),
            ],
        ),
    ]
